(()=>{"use strict";
const W=window.LIZZY_TELEGRAM_WORKER_URL||"https://lizzyos-notifications.mulaudzimikael73.workers.dev/";
const $=id=>document.getElementById(id);let game=new Chess(),selected=null,lastFen="";
const esc=s=>String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]));
const api=async(action,body={})=>{const r=await fetch(W+"?action="+encodeURIComponent(action),{method:Object.keys(body).length?"POST":"GET",headers:{"Content-Type":"application/json"},body:Object.keys(body).length?JSON.stringify({action,...body}):undefined,cache:"no-store"});const d=await r.json();if(!r.ok||d.success===false)throw new Error(d.error||"Request failed");return d};
const glyph={p:"♟",r:"♜",n:"♞",b:"♝",q:"♛",k:"♚",P:"♙",R:"♖",N:"♘",B:"♗",K:"♔",Q:"♕"};
function render(){const b=$("board");b.innerHTML="";const bd=game.board();for(let r=0;r<8;r++)for(let c=0;c<8;c++){const sq=String.fromCharCode(97+c)+(8-r),p=bd[r][c];const x=document.createElement("button");x.className="sq "+((r+c)%2?"dark":"light");if(selected===sq)x.classList.add("selected");if(selected){try{if(game.moves({square:selected,verbose:true}).some(m=>m.to===sq))x.classList.add("legal")}catch{}}x.textContent=p?(p.color==="w"?glyph[p.type.toUpperCase()]:glyph[p.type]):"";x.onclick=()=>click(sq);b.appendChild(x)}$("turn").textContent=game.turn()==="w"?"🌸 Your turn — choose a white piece":"🖤 Mikael's turn — he's thinking…";$("moves").textContent=game.pgn()||"No moves yet."}
async function click(sq){if(game.turn()!=="w")return;if(!selected){const p=game.get(sq);if(!p||p.color!=="w")return;selected=sq;render();return}try{const m=game.move({from:selected,to:sq,promotion:"q"});if(!m){selected=sq;render();return}selected=null;render();await api("lizzy_chess_move",{fen:game.fen(),pgn:game.pgn(),turn:game.turn(),lastMove:m.san});}catch(e){alert(e.message);loadChess()}}
async function loadChess(){try{const d=await api("coop_chess"),s=d.state;if(s.fen&&s.fen!=="start"&&s.fen!==lastFen){game.load(s.fen);lastFen=s.fen}else if(s.fen==="start"&&lastFen!=="start"){game=new Chess();lastFen="start"}render();}catch(e){$("turn").textContent="Chess is unavailable right now."}}
async function help(text){try{await api("lizzy_chess_help",{text});$("hintBox").textContent="💌 Mikael has been notified. Wait for his advice."; }catch(e){$("hintBox").textContent=e.message}}
document.querySelectorAll("[data-help]").forEach(b=>b.onclick=()=>help(b.dataset.help));$("askHelp").onclick=()=>{const t=$("customHelp").value.trim();if(t){$("customHelp").value="";help(t)}}; 
async function escapeLoad(){try{const d=await api("coop_escape"),s=d.state||{};$("escapeStatus").textContent=s.status==="active"?"🟢 Room active":"Waiting for Mikael to start the room";$("lizzyClues").innerHTML=(s.lizzyClues||[]).map(x=>`<div class="clue">${esc(x)}</div>`).join("");$("chat").innerHTML=(s.chat||[]).map(x=>`<div><b>${esc(x.from)}:</b> ${esc(x.text)}</div>`).join("");$("chat").scrollTop=$("chat").scrollHeight}catch(e){$("escapeStatus").textContent="Escape room unavailable."}}
$("chatSend").onclick=async()=>{const t=$("chatInput").value.trim();if(!t)return;try{await api("lizzy_escape_chat",{text:t});$("chatInput").value="";escapeLoad()}catch(e){alert(e.message)}};$("chatInput").onkeydown=e=>{if(e.key==="Enter")$("chatSend").click()};
document.querySelectorAll(".tabs button").forEach(b=>b.onclick=()=>{document.querySelectorAll(".tabs button").forEach(x=>x.classList.remove("active"));b.classList.add("active");document.querySelectorAll(".tab").forEach(x=>x.classList.add("hidden"));$(b.dataset.tab).classList.remove("hidden");if(b.dataset.tab==="escape")escapeLoad()});
$("back").onclick=()=>history.back();
loadChess();setInterval(loadChess,3000);setInterval(()=>{if(!$("escape").classList.contains("hidden"))escapeLoad()},3000);
})();